### ISSUE TITLE
Slide 

### ISSUE THREAD

**Issue by seroseeisero** [sakdipatr/G5A.proj-BG#21]

**Comment by Natpns9** [comment]
https://www.canva.com/design/DAF9P0Q0JtU/Txf9sdKkZtrMCvUetNMRMA/edit?utm_content=DAF9P0Q0JtU&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by Natpns9** [comment]
https://www.canva.com/design/DAF9P0Q0JtU/Txf9sdKkZtrMCvUetNMRMA/edit?utm_content=DAF9P0Q0JtU&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
